[build]
  command = "npm run build"   # or whatever your build command is
  publish = "public"          # your static assets folder



[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
